# Generated by Django 4.0.6 on 2022-07-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_img',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='vote_count',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='vote_ratio',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
