# Generated by Django 4.0.6 on 2022-07-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_featured_img_project_vote_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_img',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to=''),
        ),
    ]
